### ISSUE TITLE
integrate LoginKey as authentication

### ISSUE THREAD

**Issue by jaxmann** [kevinchesser/pmr-rest#4]
ill pass a 32 char string that is generated the same way as the salt (but wont be the same) to you in the /signup method 
/signup method needs to save it in the db (the field is called LoginKey i think) 
/signup should also set ReceiveEmails to 0 and ReceiveTexts to 0

ill also pass the 32 char string to the /login method 
save it into the db there as well 

and then ill pass the 32 char string to the /retrievePlayers, /sendFavorites, and /retrieveFavorites methods 
and each method should only proceed if the key matches whats in the db for that user 
each of those methods is already passed the user 
so you can compare it with user + key

**Comment by kevinchesser** [comment]
ReceiveEmails and ReceiveTexts set to current time + 5 years

**Comment by kevinchesser** [comment]
/retrievePlayers /sendFavorites and /retrieveFavorites done - closing issue
