### ISSUE TITLE
modify time stamps

### ISSUE THREAD

**Issue by jaxmann** [kevinchesser/pmr-rest#7]
receiveEmails; true -> time set to past
receiveEmails: false -> time set to 3000
disable notification -> set time into future for that many hours

when sending emails, check if their time is in the future, then dont send email, else send email

**Comment by kevinchesser** [comment]
sending emails has to do with the server not pmr-rest

**Comment by jaxmann** [comment]
yes but the time setting is pmr-rest. the send email is just an instruction to myself

**Comment by kevinchesser** [comment]
Yeah I was only commenting on that part. I knew the rest was for rest

**Comment by kevinchesser** [comment]
Dealt with in issue #6
